title: "我的文档"
description: "我的文档在线阅读"
author: "作者"
lang: "zh-CN"
theme: minima
baseurl: "/qinmo-hanwangchao"
url: ""
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - .history
  - .chapter-project.json
